language: c
compiler:
  - gcc
  - clang

os:
  - linux

cache:
  directories:
    - dpdk-dir

addons:
  apt:
    packages:
      - bc
      - libssl-dev
      - llvm-dev
      - libjemalloc1
      - libjemalloc-dev
      - libnuma-dev
      - libpcap-dev
      - python3-openssl
      - python3-pip
      - python3-sphinx
      - libelf-dev
      - selinux-policy-dev
      - libunbound-dev
      - libunwind-dev

before_install: ./.travis/${TRAVIS_OS_NAME}-prepare.sh

before_script: export PATH=$PATH:$HOME/bin

env:
  - WITH_P4=1 TESTSUITE=1
  - WITH_P4=1 DPDK=1
  - WITH_P4=1 AFXDP=1 KERNEL=5.3
  - WITH_P4=1 DPDK=1 OPTS="--enable-shared"
  - DPDK_SHARED=1
  - DPDK_SHARED=1 OPTS="--enable-shared"

#matrix:
#  include:
#    - os: osx
#      compiler: clang
#      env: OPTS="--disable-ssl"
#    - arch: arm64
#      compiler: gcc
#      env: TESTSUITE=1 DPDK=1
#    - arch: arm64
#      compiler: gcc
#      env: KERNEL_LIST="5.5 4.19"
#    - arch: arm64
#      compiler: gcc
#      env: KERNEL_LIST="4.9 3.16"
#    - arch: arm64
#      compiler: gcc
#      env: DPDK_SHARED=1
#    - arch: arm64
#      compiler: clang
#      env: OPTS="--disable-ssl"

script: ./.travis/${TRAVIS_OS_NAME}-build.sh $OPTS

notifications:
  email:
    recipients:
      - osinstom@gmail.com
